source 'https://rubygems.org'
ruby '2.2.4'
gem 'rails', '4.2.5'
gem 'pg'
gem 'sass-rails', '~> 5.0.0'
gem 'foundation-rails', '~> 5.5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'devise-i18n'
gem 'high_voltage'
gem 'rails-i18n'
gem 'paperclip'
gem 'active_hash'
gem 'rails-html-sanitizer'
gem 'react-rails', '~> 1.5.0'
gem 'aws-sdk', '< 2.0'
gem 'puma'
gem 'simple_form'
gem 'figaro'
gem 'rails_12factor', group: :production
gem 'rqrcode', '~> 0.10.1'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_20]
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rainbow'
end